### ISSUE TITLE
Issue with PMPRO

### ISSUE THREAD

**Issue by driftywinds** [db55falcon/Boost_Manager#1]
After installation this is the error it gives me when i run "main.exe" from the PMPRO folder: -
```
Traceback (most recent call last):
  File "pywinauto\application.py", line 1038, in start
pywintypes.error: (740, 'CreateProcess', 'The requested operation requires elevation.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 14, in <module>
  File "pywinauto\application.py", line 1052, in start
pywinauto.application.AppStartError: Could not create the process "OpenHardwareMonitor\OpenHardwareMonitor.exe"
Error returned by CreateProcess: (740, 'CreateProcess', 'The requested operation requires elevation.')
```

**Comment by db55falcon** [comment]
Hey, you need to right click and run as administrator

**Comment by driftywinds** [comment]
That fixed it, thanks!

**Comment by db55falcon** [comment]
Great, if you find bugs or defects lmk. Thanks!

**Comment by driftywinds** [comment]
> Great, if you find bugs or defects lmk. Thanks!

no bugs yet, but id like to suggest a feature of allowing the program to startup with windows minimized (can be accessed through the taskbar tray), that way its handy to use and always there, ready to enable/disable boost.
